name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"

jobs:
  go_unit_tests:
    name: Go unit tests
    runs-on: ubuntu-18.04
    container:
      image: golang:1.14.2
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Go unit tests
      run: |
        go test -cover -race -v -mod=readonly ./...
